---
allow_list:
  - bugs.debian.org
  - changelogs.ubuntu.com
  - download.docker.com
  - www.ui.com
  - dl.ui.com
  - dl.ubnt.com

allow_list_escaped: "{{ allow_list | replace('.', '\\.') }}"

allow_string: "{{ allow_list_escaped | join('|') }}"
