---
- name: 'Install Charlotte temp dependencies'
  apt:
    name: ['git', 'bc']
    state: latest
    update_cache: yes

- name: 'Download Charlotte project'
  git: repo=https://github.com/arobb/charlotte.git dest=/home/pi/git/charlotte

- name: 'Install and start temperature reporting'
  shell:
    chdir: '/home/pi/git/charlotte'
    cmd: 'install/install_service_temperature.sh'
